
name: Continuous integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pipeline:
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        all: ${{ steps.changes.outputs.all}}
        ts: ${{ steps.changes.outputs.py }}      
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 1

        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
              python-version: 3.9

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Test example01 Max
          run: |
              pytest -v _test_/example01/test_max_value.py
              

        - name: Test example01 Min
          run: |
              pytest -v _test_/example01/test_min_value.py

        - name: Test example02 Max
          run: |
              pytest -v _test_/example02/test_prod_array.py
              

        - name: Test example02 Min
          run: |
              pytest -v _test_/example02/test_sum_array.py

        - name: Display the path
          run: |
            import os
            print(os.environ['PATH'])
          shell: python

        - name: 
          run: |
            echo ${{ github.ref }}
            echo ${{ github.head_ref || github.run_id }}
            echo ${{ github.workflow }}-${{ github.ref }}
            echo ${{ github.action }}
            echo ${{ github.action_path }}
            echo ${{ github.action_repository }}
            echo ${{ github.action_status }}
            echo ${{ github.actor }}
            echo ${{ github.api_url }}
            echo ${{ github.base_ref }}
            echo ${{ github.env }}
            echo ${{ github.event_name }}
            echo ${{ github.event_path }}
            echo ${{ github.graphql_url }}            
            echo ${{ github.head_ref }}
            echo ${{ github.job }}
            echo ${{ github.ref }}
            echo ${{ github.ref_name }}
            echo ${{ github.ref_protected }}
            echo ${{ github.ref_type }}
            echo ${{ github.path }}
            echo ${{ github.repository }}
            echo ${{ github.repository_owner }}
            echo ${{ github.repositoryUrl }}
            echo ${{ github.retention_days }}
            echo ${{ github.run_id }}
            echo ${{ github.run_number }}
            echo ${{ github.run_attempt }}
            echo ${{ github.server_url }} 
            echo ${{ github.sha }}
            echo ${{ github.token }}
            echo ${{ github.triggering_actor }}
            echo ${{ github.workflow }}
            echo ${{ github.workspace }}


            

            