name: Auto-approve PRs with passing reviews and checks

on:
  pull_request:
    types: [closed, reopened]
    branches: [main]

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Check for reviews
        uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.pull_request.requested_reviewers.length === 0 || context.payload.pull_request.requested_reviewers.every(reviewer => reviewer.state === 'APPROVED')) {
              console.log('All reviewers have approved, proceeding to check for passing checks.');
            } else {
              console.log('Not all reviewers have approved, skipping auto-approval.');
              exit();
            }
      - name: Check for passing checks
        uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.pull_request.checks.every(check => check.status === 'completed' && check.conclusion === 'success')) {
              console.log('All checks have passed, approving pull request.');
            } else {
              console.log('Not all checks have passed, skipping auto-approval.');
              exit();
            }
      - name: Approve pull request
        uses: actions/github-script@v6
        with:
          script: |
            github.pullRequests.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              review: {
                state: 'APPROVED'
              }
            });
